### PR TITLE
Cleanup / Reorganize Repo

### PR DESCRIPTION
**Pull request by codekow**

### CODE REVIEW

**Review by zachab4 — CHANGES_REQUESTED** [review]
Should [Dockerfile](https://github.com/codekow/ocp-code-server/tree/main/container/base/Dockerfile) be restructured to ubi and codercom directories?  Current structure means all of the codercom builds will fail b/c the sybolic link sends to ubi base and patch dockerfiles.

**Comment by codekow** [comment]
@zachab4 Take a look now. 

I have tested the builds and they work. I don't see the issues you mention with path.

**Comment by zachab4** [comment]
> @zachab4 Take a look now.
> 
> I have tested the builds and they work. I don't see the issues you mention with path.

I missed "dockerfilePath: Dockerfile.codercom" in the templates

**Review by zachab4 — APPROVED** [review]
Looks good

**Pull request merged**
